### ISSUE TITLE
XA模式执行示例代码报错

### ISSUE THREAD

**Issue by tw2066** [dtm-php/dtm-client#59]
执行文档中的XA示例代码

报错

```
 PDOException: SQLSTATE[XAE07]: <<Unknown error>>: 1399 XAER_RMFAIL: The command cannot be executed when global transaction is in the  ACTIVE state in /Users/WWW/php-service/vendor/dtm/dtm-client/src/DbTransaction/AbstractTransaction.php:57
Stack trace:
#0 /Users/WWW/php-service/vendor/dtm/dtm-client/src/DbTransaction/AbstractTransaction.php(57): PDO->exec('XA rollback 'Wn...')
#1 /Users/WWW/php-service/vendor/dtm/dtm-client/src/DtmImp.php(83): DtmClient\DbTransaction\AbstractTransaction->xaExec('XA rollback 'Wn...')
#2 /Users/WWW/php-service/vendor/dtm/dtm-client/src/XA.php(75): DtmClient\DtmImp->xaHandleLocalTrans(Object(Closure))

```

**Comment by PandaLIU-1111** [comment]
你是不是用了xa还开事物了

**Comment by tw2066** [comment]
没有的, 就直接运行  https://github.com/dtm-php/dtm-sample 代码, 也是报错

**Comment by PandaLIU-1111** [comment]
> 没有的, 就直接运行 https://github.com/dtm-php/dtm-sample 代码, 也是报错

我这边无法复现，我执行的是 `/xa/successCase` 这个 API，能说明一下你的复现步骤不，还有环境说明

**Comment by tw2066** [comment]
* 看了一下 , 没看执行迁移文件; 没有barrier表
   很奇怪的是 报的是`The command cannot be executed when global transaction is in the  ACTIVE state`错误
* 执行完成迁移文件后
   第一次返回数据 http://127.0.0.1:9501/xa/successCase 返回 mftfFTFgMSxd6L5m8UXYkd, 但是数据没有改
   再次请求
   
```
   Client error: `POST http://127.0.0.1:36789/api/dtmsvr/abort` resulted in a `409 Conflict` response:
{"dtm_result":"FAILURE","message":"trans type: 'xa' current status 'failed', cannot abort. FAILURE"}
   ```

 数据库执行SQL
 ```
UPDATE `activity` set `is_enabled` = `is_enabled` + 1 where id = 2
 1205 - Lock wait timeout exceeded; try restarting transaction
 Time: 51.736s
```


<img width="846" alt="image" src="https://user-images.githubusercontent.com/24579418/221461056-3194dfbe-b605-40cc-94d3-725294722d54.png">

**Comment by tw2066** [comment]
复现步骤:
1.拉取代码: https://github.com/dtm-php/dtm-sample
2.修改compose.json
```
{
    "name": "hyperf/hyperf-skeleton",
    "type": "project",
    "keywords": [
        "php",
        "swoole",
        "framework",
        "hyperf",
        "microservice",
        "middleware"
    ],
    "description": "A coroutine framework that focuses on hyperspeed and flexible, specifically use for build microservices and middlewares.",
    "license": "Apache-2.0",
    "require": {
        "php": ">=8.0",
        "dtm/dtm-client": "*",
        "hyperf/cache": "~2.2.0",
        "hyperf/command": "~2.2.0",
        "hyperf/config": "~2.2.0",
        "hyperf/database": "~2.2.0",
        "hyperf/db": "^2.2",
        "hyperf/db-connection": "^2.2",
        "hyperf/framework": "~2.2.0",
        "hyperf/grpc-client": "^2.2",
        "hyperf/grpc-server": "^2.2",
        "hyperf/guzzle": "~2.2.0",
        "hyperf/http-server": "~2.2.0",
        "hyperf/json-rpc": "^2.2",
        "hyperf/logger": "~2.2.0",
        "hyperf/memory": "~2.2.0",
        "hyperf/process": "~2.2.0",
        "hyperf/redis": "~2.2.0"
    },
    "require-dev": {
        "friendsofphp/php-cs-fixer": "^3.0",
        "hyperf/devtool": "~2.2.0",
        "hyperf/ide-helper": "~2.2.0",
        "hyperf/testing": "~2.2.0",
        "mockery/mockery": "^1.0",
        "phpstan/phpstan": "^0.12",
        "swoole/ide-helper": "^4.5"
    },
    "suggest": {
        "ext-openssl": "Required to use HTTPS.",
        "ext-json": "Required to use JSON.",
        "ext-pdo": "Required to use MySQL Client.",
        "ext-pdo_mysql": "Required to use MySQL Client.",
        "ext-redis": "Required to use Redis Client."
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "files": []
    },
    "autoload-dev": {
        "psr-4": {
            "HyperfTest\\": "./test/"
        }
    },
    "prefer-stable": true,
    "config": {
        "optimize-autoloader": true,
        "sort-packages": true
    },
    "extra": [],
    "scripts": {
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-autoload-dump": [
            "rm -rf runtime/container"
        ],
        "test": "co-phpunit --prepend test/bootstrap.php -c phpunit.xml --colors=always",
        "cs-fix": "php-cs-fixer fix $1",
        "analyse": "phpstan analyse --memory-limit 300M -l 0 -c phpstan.neon ./app ./config",
        "start": [
            "Composer\\Config::disableProcessTimeout",
            "php ./bin/hyperf.php start"
        ]
    }
}

```
3. composer update
4. 执行数据库迁移命令, 生成barrier表 和 手动创建order表
5. 启动服务 
6. 访问 http://127.0.0.1:9502/xa/successCase  第一次返回数据 返回 mftfFTFgMSxd6L5m8UXYkd, 但是数据没有改
再次请求
```
   Client error: `POST http://127.0.0.1:36789/api/dtmsvr/abort` resulted in a `409 Conflict` response:
{"dtm_result":"FAILURE","message":"trans type: 'xa' current status 'failed', cannot abort. FAILURE"}
```
7.msyql版本  5.7.41

**Comment by PandaLIU-1111** [comment]
好的，我晚点看看

**Comment by PandaLIU-1111** [comment]
> 6.访问 http://127.0.0.1:9502/xa/successCase 第一次返回数据 返回 mftfFTFgMSxd6L5m8UXYkd, 但是数据没有改
再次请求

我这边无法复现，我测了都可以正常的修改到数据

**Comment by PandaLIU-1111** [comment]
加一下我微信吧，和你确认一下复现步骤 jian563883861

**Comment by PandaLIU-1111** [comment]
XA 事务，报 `SQLSTATE[XAE07]: <<Unknown error>>: 1399 XAER_RMFAIL: The command cannot be executed when global transaction is in the  ACTIVE state[57]` 请检查一下 order 表是否有设置 `id` 为主键
